// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuoteManager.Infrastructure.Persistence;

#nullable disable

namespace QuoteManager.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(QuoteManagerDbContext))]
    [Migration("20260729154334_AddOrganizationRetiredAt")]
    partial class AddOrganizationRetiredAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("QuoteManager.Domain.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RetiredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Organizations", (string)null);
                });

            modelBuilder.Entity("QuoteManager.Domain.Quotes.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusChangedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VendorOrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Amount", "QuoteManager.Domain.Quotes.Quote.Amount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("Amount")
                                .HasColumnType("INTEGER")
                                .HasColumnName("AmountMinorUnits");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("CurrencyCode");
                        });

                    b.HasKey("Id");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("UX_Quotes_OneAcceptedPerRequest")
                        .HasFilter("\"Status\" = 'Accepted'");

                    b.HasIndex("VendorOrganizationId");

                    b.HasIndex("Status", "ExpiresAt");

                    b.ToTable("Quotes", (string)null);
                });

            modelBuilder.Entity("QuoteManager.Domain.Requests.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientOrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("NeededBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientOrganizationId");

                    b.HasIndex("Status");

                    b.ToTable("Requests", (string)null);
                });

            modelBuilder.Entity("QuoteManager.Domain.Requests.RequestInvitation", b =>
                {
                    b.Property<Guid>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VendorOrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvitedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RequestId", "VendorOrganizationId");

                    b.HasIndex("VendorOrganizationId");

                    b.ToTable("RequestInvitations", (string)null);
                });

            modelBuilder.Entity("QuoteManager.Infrastructure.Identity.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("QuoteManager.Infrastructure.Persistence.Entities.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OccurredAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("SubjectType", "SubjectId", "OccurredAt");

                    b.ToTable("AuditEntries", (string)null);
                });

            modelBuilder.Entity("QuoteManager.Infrastructure.Persistence.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DispatchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OccurredAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DispatchedAt", "OccurredAt");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("QuoteManager.Infrastructure.Persistence.Entities.QuoteStatusLookup", b =>
                {
                    b.Property<string>("Status")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Status");

                    b.ToTable("QuoteStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Status = "Draft",
                            DisplayOrder = 0,
                            IsTerminal = false
                        },
                        new
                        {
                            Status = "Submitted",
                            DisplayOrder = 1,
                            IsTerminal = false
                        },
                        new
                        {
                            Status = "UnderReview",
                            DisplayOrder = 2,
                            IsTerminal = false
                        },
                        new
                        {
                            Status = "Accepted",
                            DisplayOrder = 3,
                            IsTerminal = true
                        },
                        new
                        {
                            Status = "Rejected",
                            DisplayOrder = 4,
                            IsTerminal = true
                        },
                        new
                        {
                            Status = "Withdrawn",
                            DisplayOrder = 5,
                            IsTerminal = true
                        },
                        new
                        {
                            Status = "Expired",
                            DisplayOrder = 6,
                            IsTerminal = true
                        });
                });

            modelBuilder.Entity("QuoteManager.Domain.Quotes.Quote", b =>
                {
                    b.HasOne("QuoteManager.Domain.Requests.Request", null)
                        .WithMany("Quotes")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuoteManager.Infrastructure.Persistence.Entities.QuoteStatusLookup", null)
                        .WithMany()
                        .HasForeignKey("Status")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuoteManager.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("VendorOrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuoteManager.Domain.Requests.Request", b =>
                {
                    b.HasOne("QuoteManager.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("ClientOrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuoteManager.Domain.Requests.RequestInvitation", b =>
                {
                    b.HasOne("QuoteManager.Domain.Requests.Request", null)
                        .WithMany("Invitations")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuoteManager.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("VendorOrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuoteManager.Infrastructure.Identity.AppUser", b =>
                {
                    b.HasOne("QuoteManager.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("QuoteManager.Domain.Requests.Request", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("Quotes");
                });
#pragma warning restore 612, 618
        }
    }
}
